version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage-app
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    networks:
      - storage-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_HOST=redis:6379

  mongodb:
    image: mongo:latest
    container_name: storage-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - storage-network

  redis:
    image: redis:latest
    container_name: storage-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - storage-network

networks:
  storage-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
